package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Offers generated by hbm2java
 */
public class Offers implements java.io.Serializable {

	private Integer offerId;
	private Cleaners cleaners;
	private byte[] offerType;
	private String desc;
	private boolean scheduled;
	private String day;
	private String time;
	private Set opinionses = new HashSet(0);
	private Set orderses = new HashSet(0);

	public Offers() {
	}

	public Offers(Cleaners cleaners, byte[] offerType, boolean scheduled) {
		this.cleaners = cleaners;
		this.offerType = offerType;
		this.scheduled = scheduled;
	}

	public Offers(Cleaners cleaners, byte[] offerType, String desc,
			boolean scheduled, String day, String time, Set opinionses,
			Set orderses) {
		this.cleaners = cleaners;
		this.offerType = offerType;
		this.desc = desc;
		this.scheduled = scheduled;
		this.day = day;
		this.time = time;
		this.opinionses = opinionses;
		this.orderses = orderses;
	}

	public Integer getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Integer offerId) {
		this.offerId = offerId;
	}

	public Cleaners getCleaners() {
		return this.cleaners;
	}

	public void setCleaners(Cleaners cleaners) {
		this.cleaners = cleaners;
	}

	public byte[] getOfferType() {
		return this.offerType;
	}

	public void setOfferType(byte[] offerType) {
		this.offerType = offerType;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public boolean isScheduled() {
		return this.scheduled;
	}

	public void setScheduled(boolean scheduled) {
		this.scheduled = scheduled;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Set getOpinionses() {
		return this.opinionses;
	}

	public void setOpinionses(Set opinionses) {
		this.opinionses = opinionses;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
