package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Resources generated by hbm2java
 */
public class Resources implements java.io.Serializable {

	private Integer resourceId;
	private String name;
	private int quantity;
	private String desc;
	private Set cleanerReses = new HashSet(0);

	public Resources() {
	}

	public Resources(String name, int quantity) {
		this.name = name;
		this.quantity = quantity;
	}

	public Resources(String name, int quantity, String desc, Set cleanerReses) {
		this.name = name;
		this.quantity = quantity;
		this.desc = desc;
		this.cleanerReses = cleanerReses;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Set getCleanerReses() {
		return this.cleanerReses;
	}

	public void setCleanerReses(Set cleanerReses) {
		this.cleanerReses = cleanerReses;
	}

}
