package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String lastName;
	private boolean sex;
	private String login;
	private String password;
	private String email;
	private Integer phoneNum;
	private int authLvl;
	private String locality;
	private String streetAddr;
	private String postalCode;
	private String postLoc;
	private Set customerses = new HashSet(0);
	private Set cleanerses = new HashSet(0);

	public Users() {
	}

	public Users(String name, String lastName, boolean sex, String login,
			String password, String email, int authLvl) {
		this.name = name;
		this.lastName = lastName;
		this.sex = sex;
		this.login = login;
		this.password = password;
		this.email = email;
		this.authLvl = authLvl;
	}

	public Users(String name, String lastName, boolean sex, String login,
			String password, String email, Integer phoneNum, int authLvl,
			String locality, String streetAddr, String postalCode,
			String postLoc, Set customerses, Set cleanerses) {
		this.name = name;
		this.lastName = lastName;
		this.sex = sex;
		this.login = login;
		this.password = password;
		this.email = email;
		this.phoneNum = phoneNum;
		this.authLvl = authLvl;
		this.locality = locality;
		this.streetAddr = streetAddr;
		this.postalCode = postalCode;
		this.postLoc = postLoc;
		this.customerses = customerses;
		this.cleanerses = cleanerses;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public boolean isSex() {
		return this.sex;
	}

	public void setSex(boolean sex) {
		this.sex = sex;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(Integer phoneNum) {
		this.phoneNum = phoneNum;
	}

	public int getAuthLvl() {
		return this.authLvl;
	}

	public void setAuthLvl(int authLvl) {
		this.authLvl = authLvl;
	}

	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public String getStreetAddr() {
		return this.streetAddr;
	}

	public void setStreetAddr(String streetAddr) {
		this.streetAddr = streetAddr;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPostLoc() {
		return this.postLoc;
	}

	public void setPostLoc(String postLoc) {
		this.postLoc = postLoc;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

	public Set getCleanerses() {
		return this.cleanerses;
	}

	public void setCleanerses(Set cleanerses) {
		this.cleanerses = cleanerses;
	}

}
