-- MySQL Script generated by MySQL Workbench
-- 04/11/15 13:28:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TekiCleanDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TekiCleanDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TekiCleanDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `TekiCleanDB` ;

-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `phone_num` INT(11) NULL,
  `auth_lvl` INT NOT NULL,
  `locality` VARCHAR(45) NULL,
  `street_addr` VARCHAR(45) NULL,
  `postal_code` VARCHAR(6) NULL,
  `post_loc` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `dorm_num` INT NULL,
  `room` INT NULL,
  `dorm_addres` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_Customers_Users_idx` (`user_id` ASC),
  CONSTRAINT `fk_Customers_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `TekiCleanDB`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Cleaners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Cleaners` (
  `cleaner_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`cleaner_id`),
  INDEX `fk_Cleaners_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Cleaners_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TekiCleanDB`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Offers` (
  `offer_id` INT NOT NULL AUTO_INCREMENT,
  `cleaner_id` INT NOT NULL,
  `offer_type` BINARY(3) NOT NULL DEFAULT 110,
  `desc` TEXT(500) NULL,
  `scheduled` TINYINT(1) NOT NULL DEFAULT 0,
  `day` VARCHAR(3) NULL,
  `time` VARCHAR(5) NULL,
  PRIMARY KEY (`offer_id`),
  INDEX `fk_Offers_Cleaners1_idx` (`cleaner_id` ASC),
  CONSTRAINT `fk_Offers_Cleaners1`
    FOREIGN KEY (`cleaner_id`)
    REFERENCES `TekiCleanDB`.`Cleaners` (`cleaner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Opinions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Opinions` (
  `opinion_id` INT NOT NULL AUTO_INCREMENT,
  `offer_id` INT NULL,
  `cleaner_id` INT NULL,
  `text` TEXT(500) NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`opinion_id`),
  INDEX `fk_Opinions_Offers1_idx` (`offer_id` ASC),
  INDEX `fk_Opinions_Cleaners1_idx` (`cleaner_id` ASC),
  CONSTRAINT `fk_Opinions_Offers1`
    FOREIGN KEY (`offer_id`)
    REFERENCES `TekiCleanDB`.`Offers` (`offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Opinions_Cleaners1`
    FOREIGN KEY (`cleaner_id`)
    REFERENCES `TekiCleanDB`.`Cleaners` (`cleaner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Resources` (
  `resource_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  `desc` TEXT(250) NULL,
  PRIMARY KEY (`resource_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Schedules` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `cleaner_id` INT NOT NULL,
  `day` INT NULL,
  `time_range` VARCHAR(45) NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_Schedules_Cleaners1_idx` (`cleaner_id` ASC),
  CONSTRAINT `fk_Schedules_Cleaners1`
    FOREIGN KEY (`cleaner_id`)
    REFERENCES `TekiCleanDB`.`Cleaners` (`cleaner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Cleaner_res`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Cleaner_res` (
  `cleaner_res_id` INT NOT NULL AUTO_INCREMENT,
  `resource_id` INT NOT NULL,
  `cleaner_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `state` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cleaner_res_id`),
  INDEX `fk_Cleaner_res_Resources1_idx` (`resource_id` ASC),
  INDEX `fk_Cleaner_res_Cleaners1_idx` (`cleaner_id` ASC),
  CONSTRAINT `fk_Cleaner_res_Resources1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `TekiCleanDB`.`Resources` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cleaner_res_Cleaners1`
    FOREIGN KEY (`cleaner_id`)
    REFERENCES `TekiCleanDB`.`Cleaners` (`cleaner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TekiCleanDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TekiCleanDB`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `Offers_offer_id` INT NOT NULL,
  `term` DATE NULL,
  `state` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Orders_Customers1_idx` (`customer_id` ASC),
  INDEX `fk_Orders_Offers1_idx` (`Offers_offer_id` ASC),
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `TekiCleanDB`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Offers1`
    FOREIGN KEY (`Offers_offer_id`)
    REFERENCES `TekiCleanDB`.`Offers` (`offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
