package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Cleaners generated by hbm2java
 */
public class Cleaners implements java.io.Serializable {

	private Integer cleanerId;
	private Users users;
	private ArrayList<CleanerRes> cleanerReses = new ArrayList<CleanerRes>();
	private ArrayList<Offers> offerses = new ArrayList<Offers>();
	private ArrayList<Opinions> opinionses = new ArrayList<Opinions>();
	private ArrayList<Schedules> scheduleses = new ArrayList<Schedules>();

	public Cleaners() {
	}

	public Cleaners(Users users) {
		this.users = users;
	}

	public Cleaners(Users users, ArrayList<CleanerRes> cleanerReses, ArrayList<Offers> offerses,
			ArrayList<Opinions> opinionses, ArrayList<Schedules> scheduleses) {
		this.users = users;
		this.cleanerReses = cleanerReses;
		this.offerses = offerses;
		this.opinionses = opinionses;
		this.scheduleses = scheduleses;
	}

	public Integer getCleanerId() {
		return this.cleanerId;
	}

	public void setCleanerId(Integer cleanerId) {
		this.cleanerId = cleanerId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public ArrayList<CleanerRes> getCleanerReses() {
		return this.cleanerReses;
	}

	public void setCleanerReses(ArrayList<CleanerRes> cleanerReses) {
		this.cleanerReses = cleanerReses;
	}

	public ArrayList<Offers> getOfferses() {
		return this.offerses;
	}

	public void setOfferses(ArrayList<Offers> offerses) {
		this.offerses = offerses;
	}

	public ArrayList<Opinions> getOpinionses() {
		return this.opinionses;
	}

	public void setOpinionses(ArrayList<Opinions> opinionses) {
		this.opinionses = opinionses;
	}

	public ArrayList<Schedules> getScheduleses() {
		return this.scheduleses;
	}

	public void setScheduleses(ArrayList<Schedules> scheduleses) {
		this.scheduleses = scheduleses;
	}

}
