package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

/**
 * Opinions generated by hbm2java
 */
public class Opinions implements java.io.Serializable {

	private Integer opinionId;
	private Cleaners cleaners;
	private Offers offers;
	private String text;
	private int rate;

	public Opinions() {
	}

	public Opinions(String text, int rate) {
		this.text = text;
		this.rate = rate;
	}

	public Opinions(Cleaners cleaners, Offers offers, String text, int rate) {
		this.cleaners = cleaners;
		this.offers = offers;
		this.text = text;
		this.rate = rate;
	}

	public Integer getOpinionId() {
		return this.opinionId;
	}

	public void setOpinionId(Integer opinionId) {
		this.opinionId = opinionId;
	}

	public Cleaners getCleaners() {
		return this.cleaners;
	}

	public void setCleaners(Cleaners cleaners) {
		this.cleaners = cleaners;
	}

	public Offers getOffers() {
		return this.offers;
	}

	public void setOffers(Offers offers) {
		this.offers = offers;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public int getRate() {
		return this.rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}

}
