package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer orderId;
	private Customers customers;
	private Offers offers;
	private Date term;
	private Integer state;

	public Orders() {
	}

	public Orders(Customers customers, Offers offers) {
		this.customers = customers;
		this.offers = offers;
	}

	public Orders(Customers customers, Offers offers, Date term, Integer state) {
		this.customers = customers;
		this.offers = offers;
		this.term = term;
		this.state = state;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Offers getOffers() {
		return this.offers;
	}

	public void setOffers(Offers offers) {
		this.offers = offers;
	}

	public Date getTerm() {
		return this.term;
	}

	public void setTerm(Date term) {
		this.term = term;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
