package teki.clean.app.domain;

// Generated 2015-05-06 23:07:10 by Hibernate Tools 3.4.0.CR1

/**
 * CleanerRes generated by hbm2java
 */
public class CleanerRes implements java.io.Serializable {

	private Integer cleanerResId;
	private Cleaners cleaners;
	private Resources resources;
	private int quantity;
	private int state;

	public CleanerRes() {
	}

	public CleanerRes(Cleaners cleaners, Resources resources, int quantity,
			int state) {
		this.cleaners = cleaners;
		this.resources = resources;
		this.quantity = quantity;
		this.state = state;
	}

	public Integer getCleanerResId() {
		return this.cleanerResId;
	}

	public void setCleanerResId(Integer cleanerResId) {
		this.cleanerResId = cleanerResId;
	}

	public Cleaners getCleaners() {
		return this.cleaners;
	}

	public void setCleaners(Cleaners cleaners) {
		this.cleaners = cleaners;
	}

	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
